### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by belowringzero** [mrbrutti/esearchy#3]
what is wrong???

bash-3.2# gem install rubyzip
Successfully installed rubyzip-0.9.4
1 gem installed
Installing ri documentation for rubyzip-0.9.4...
Installing RDoc documentation for rubyzip-0.9.4...
bash-3.2# gem install esearchy
Building native extensions.  This could take a while...
ERROR:  Error installing esearchy:
    esearchy requires FreedomCoder-rubyzip (>= 0.9.3, runtime)
bash-3.2#

**Comment by mrbrutti** [comment]
I would try to add the source http://gems.github.com/ to the gem installation. 

Could you give a little more background information on platform and try to install it with verbose mode so I can get more reference what actual package is failing ?
I know ubuntu has a few issues with some of the library dependencies and requires to install a few packages, but with out more information I canot give you an answer.

Also, it might be a good time to migrate back to the normal rubyzip. At the time of generating the package, rubyzip was not ruby-1.9 ready so I had to generate my own version (FreedomCoder-rubyzip). I guess I could change that dependency back to the default rubyzip.
