### ISSUE TITLE
Esearchy. Problem on kali linux 

### ISSUE THREAD

**Issue by inghack86** [mrbrutti/esearchy#4]
Hi. Can you help me. idownloaded Esearchy_mirai but when a try to run it on kali linu, the screem display this error:
/root/esearchy_mirai-0.3.1/lib/esearchy.rb:27:in `require_relative': /root/esearchy_mirai-0.3.1/lib/esearchy/parsers/people.rb:124: invalid multibyte char (US-ASCII) (SyntaxError)
/root/esearchy_mirai-0.3.1/lib/esearchy/parsers/people.rb:124: invalid multibyte char (US-ASCII)
/root/esearchy_mirai-0.3.1/lib/esearchy/parsers/people.rb:124: syntax error, unexpected $end, expecting ':'
                            "˚∫" : 
                               ^
    from /root/esearchy_mirai-0.3.1/lib/esearchy.rb:27:in`block in <top (required)>'
    from /root/esearchy_mirai-0.3.1/lib/esearchy.rb:25:in `each'
    from /root/esearchy_mirai-0.3.1/lib/esearchy.rb:25:in`<top (required)>'
    from /root/esearchy_mirai-0.3.1/bin/esearchy:26:in `require_relative'
    from /root/esearchy_mirai-0.3.1/bin/esearchy:26:in`<main>'

So i try to fix it including " # encoding: utf-8 "  as the first line of the file, but always display another error and go on:

/root/esearchy_mirai-0.3.1/bin/esearchy: line 18: syntax error near unexpected token `('
/root/esearchy_mirai-0.3.1/bin/esearchy: line 18:`unless Kernel.respond_to?(:require_relative)'

Can you help me ? please, i would like to use this tool !!!
My email is inghack86@yahoo.com

**Comment by mrbrutti** [comment]
Yes, I will be installing both apps in kai. and I will see if I ran into
the same issues. I will get back to you shortly. Hopefully tomorrow, if I
get sometime tonight.

On Tue, Jun 18, 2013 at 12:21 PM, inghack86 notifications@github.comwrote:

> Hi. Can you help me. idownloaded Esearchy_mirai but when a try to run it
> on kali linu, the screem display this error:
> /root/esearchy_mirai-0.3.1/lib/esearchy.rb:27:in require_relative':
> /root/esearchy_mirai-0.3.1/lib/esearchy/parsers/people.rb:124: invalid
> multibyte char (US-ASCII) (SyntaxError)
> /root/esearchy_mirai-0.3.1/lib/esearchy/parsers/people.rb:124: invalid
> multibyte char (US-ASCII)
> /root/esearchy_mirai-0.3.1/lib/esearchy/parsers/people.rb:124: syntax
> error, unexpected $end, expecting ':'
> "˚∫" :
> ^
> from /root/esearchy_mirai-0.3.1/lib/esearchy.rb:27:inblock in '
> from /root/esearchy_mirai-0.3.1/lib/esearchy.rb:25:in each'
> from /root/esearchy_mirai-0.3.1/lib/esearchy.rb:25:in'
> from /root/esearchy_mirai-0.3.1/bin/esearchy:26:in require_relative'
> from /root/esearchy_mirai-0.3.1/bin/esearchy:26:in'
> 
> So i try to fix it including " # encoding: utf-8 " as the first line of
> the file, but always display another error and go on:
> 
> /root/esearchy_mirai-0.3.1/bin/esearchy: line 18: syntax error near
> unexpected token ('
> /root/esearchy_mirai-0.3.1/bin/esearchy: line 18:unless
> Kernel.respond_to?(:require_relative)'
> 
> Can you help me ? please, i would like to use this tool !!!
> My email is inghack86@yahoo.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FreedomCoder/esearchy/issues/4
> .

## 

## 

B.Sc. Matias Pablo Brutti
Principal Security Researcher
Email : matiasbrutti@gmail.com
Site: http://www.freedomcoder.com.ar

**Comment by inghack86** [comment]
Hi did you solve the issues ? can you tell my how run it on Kali linux.

**Comment by mrbrutti** [comment]
Not yet. Work has kept me plenty busy. and I am using the time to finish the next full release. I'll will post the answer as soon as I can.

**Comment by socnetConnect** [comment]
hmm, i have the same problem, with Esearchy 0.3 on kali linux 2.0 x64

**Comment by mrbrutti** [comment]
@socnetConnect this is no longer maintained. You should take a look at https://github.com/FreedomCoder/esearchy_mirai which is newer code and little more maintained.
